name: Update random quote

on:
  schedule:
    - cron: '0 0 * * *' # Dagelijks om middernacht
  workflow_dispatch: # Handmatig starten

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Choose a random quote
        id: random-quote
        run: |
          QUOTE=$(shuf -n 1 quotes.txt)
          echo "quote=$QUOTE" >> $GITHUB_ENV

      - name: Update README with new quote
        run: |
          # Verwijder oude quote
          sed -i '/<!-- random-quote -->/,/<!-- end-random-quote -->/d' README.md
          
          # Voeg nieuwe quote toe
          echo "<!-- random-quote -->" >> README.md
          echo "$QUOTE" >> README.md
          echo "<!-- end-random-quote -->" >> README.md

      - name: Debug git status
        run: |
          echo "DEBUGGING GIT STATUS"
          git status
          git log -3 # Laat de laatste 3 commits zien voor debugging

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Controleer of er wijzigingen zijn om te committen
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Update random quote"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show git logs after commit
        if: success()
        run: git log -3
